### ISSUE TITLE
Path not relative to crate

### ISSUE THREAD

**Issue by ggwpez** [sam0x17/docify#3] opened 2023-06-09 10:15 UTC
CI output from [here](https://gitlab-stg.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5268) (not sure if you have access, so here again as file: [CI.txt](https://github.com/sam0x17/docify/files/11705160/CI.txt)).  
This happens in the monorepo after throwing all files into the monorepo. Now this does change the file path relative to the root Workspace from `frame/…` to `substrate/frame/…`.  

Would it be possible to make the paths relative to the crate instead of the workspace?

**Comment by sam0x17** [comment] 2023-06-10 23:12
With some difficulty I might be able to if I use `include_str!` and do the stuff at run-time that right now I am doing at compile-time. Will see what I can do

**Comment by sam0x17** [comment] 2023-06-10 23:14
The options look something like this:
1. re-do things to use `include_str!` like I mention above. This has some downsides since the compile-time dependencies will become runtime dependencies, so probably not practical
2. Add a way to set the name of the "desired root" package (we would set it to `frame`). Then these paths will still work
3. Change nothing and update the paths in the monorepo

**Comment by ggwpez** [comment] 2023-06-11 15:09
Should it not be able to use `CARGO_MANIFEST_DIR` and `concat!` to that or something?

**Comment by sam0x17** [comment] 2023-06-12 03:34
The problem is right now it is `embed!` not `embed`, so it is running in a proc macro so paths are relative to the proc macro crate's `CARGO_MANIFEST_DIR`, which tends to be in a completely useless location like in the cargo cache.

This whole thing can be resolved though if we do this at runtime instead of in a proc macro which I think is completely feasible. If I feature gate the `syn` dependency and others with `cfg(doc)` it shouldn't cause any issues for people who want to use docify but not have all of these dependencies.

**Comment by sam0x17** [comment] 2023-06-12 20:42
So yeah closing this, the only possible way right now is via workspace-relative paths and we are sort of fortunate that that even works. When rustc decides to give us access to true eager macro expansion, then we can find the file path of the caller and use that to get the true path to the current crate

**Closed by sam0x17** 2023-06-12 20:42 UTC
